# version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuf_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - zalongwa
    depends_on:
      - db
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: cuf_nginx
    restart: unless-stopped
    ports:
      - "8090:80"
      - "4433:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - zalongwa
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: cuf_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-cuf}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-cuf}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - zalongwa
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: cuf_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD:-password}"
    volumes:
      - redisdata:/data
    networks:
      - zalongwa
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuf_queue
    restart: unless-stopped
    command: php artisan queue:work --tries=3
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - zalongwa
    depends_on:
      - app
      - db
      - redis

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cuf_phpmyadmin
    restart: unless-stopped
    ports:
      - "9101:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - zalongwa
    depends_on:
      - db

networks:
  zalongwa:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
